### ISSUE TITLE
Birthdate not converted properly

### ISSUE THREAD

**Issue by maartendeblock** [Nascom/TeamleaderApiClient#14]
On the v2-refactor branch: When adding a contact, the model requires a DateTime object. However, it is not properly converted to the format Teamleader expects.

![image](https://user-images.githubusercontent.com/2155758/56641250-3cdf8880-6675-11e9-83fb-a7fc5a8a3c2d.png)

{&quot;errors&quot;:[{&quot;code&quot;:0,&quot;title&quot;:&quot;birthdate must be a valid date. Sample format: \&quot;**2005-12-30**\&quot;&quot;,&quot;status&quot;:400,&quot;meta&quot;:{&quot;field (truncated...)

**Comment by yoerioptr** [comment]
Hi @maartendeblock,
Thanks for reporting the issue. It should be solved by now.
