### ISSUE TITLE
Dependency fails when installing v2

### ISSUE THREAD

**Issue by maxi032** [Nascom/TeamleaderApiClient#18]
I got:  nascom/teamleader-api-client v2.x-dev requires php-http/client-implementation ^1.0|^2.0 -> no matching package found.

**Comment by mark-gerarts** [comment]
Hi @maxi032, the php-http/client-implementation is a virtual package. It essentially means that you need to have a php-http compatible HTTP client, but we don't really care which one you use.

If you want to use Guzzle for example, the following should fix your problem:

 ```
composer require "nascom/teamleader-api-client:v2.x-dev" php-http/guzzle6-adapter
```

Let us know if this solves it for you!
