### ISSUE TITLE
Get requests not working as expected

### ISSUE THREAD

**Issue by reyostallenberg** [Nascom/TeamleaderApiClient#21]
I think this problem that occurs now has to do with a Teamleader API update, of [feb 2022](https://developer.teamleader.eu/#/introduction/changes-&-upgrades/types-of-changes), but there is no notice of it in that docs.

Since last week I got responses like this when doing a GET:
```
Client error: `GET https://api.focus.teamleader.eu/companies.info` resulted in a `400 Bad Request` response:
{"errors":[{"code":0,"title":"id must be present","status":400,"meta":{"field":"id"}}]}
```

Fix -> Adding this:
```php
        if ($psrRequest->getMethod() == 'GET') {
            $psrRequest = $psrRequest->withUri($psrRequest->getUri()->withQuery(http_build_query($body)));
        }
```

Here https://github.com/Nascom/TeamleaderApiClient/blob/v2/src/Http/ApiClient/ApiClient.php#L110

Do you think that's a good solution?

**Comment by rgeerolf** [comment]
Adding this fix solved the issue for me. Thanks!

**Comment by mark-gerarts** [comment]
The Teamleader documentation says the following:

> All methods must be called using HTTPS. Data is passed as JSON data in a POST request or as GET query parameters.

So we were doing GET requests the wrong way in the first place by not using query parameters. Your solution seems the way to go.

Until this is implemented, an alternate approach without modifying the source would be to force a POST request (which is equally valid):

```php
$request = new CompaniesInfoRequest('some-company-id');
$request->setMethod('POST');
```

**Comment by reyostallenberg** [comment]
I'm sorry. This claim of me was false.
I'm using my own http client and forgot to add the content-type header by default.
This should be `"Content-Type": "application/json"`.
